### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by thayeylolu** [UBC-MDS/netflixpy_dashboard#55]
- [x] Address feedback from previous milestones 
- [x] Address peer review feedback
- [x] Pick one Package - R or Python
- [x] Include five improvement to APP
- [x] Add more issues to/in the repo
- [x] put together IA to make R app
- [x] Compare the Python and R app for similarity
- [x] Update read me with : r app link and image or gif or R app in action
- [x] Create a section for the link to your app
- [x] Reflection
- [x] Include the following in the About
      - A short description of your app (might already be there)
      - The link to deployed dashboard (it is often useful to still keep this in the README as well)
      - A few keywords describing which plots, widgets, and interactions you have used in your dashboards, [like it has been done this demo app](https://github.com/UBC-MDS/dashr-heroku-deployment-demo).
   
- [x] Create release
- [x] Submit to grade scope
